### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Quramy** [izumin5210/json-schema-parser#1]
日本語で失礼します. 

下記を実行すると、標題のErrorが発生しました.

``` js
'use strict';

var data = require('./sourcemap-v3.json');
var parser = require('json-schema-parser');

parser.parse(data);
```
- [sourcemap-v3.json](http://json.schemastore.org/sourcemap-v3.json)

おそらく、対象のschema中にトップレベルへの参照が貼られているため、この部分の解析中に無限ループに陥るのだと思います.

``` json
"map": {
   "$ref": "#"
}
```

以前に(別言語ですが)JSON Schemaの解析に迫られた際に、やはりこの循環参照問題に頭を悩ませたことがあります.
「parserを自作し、Schemaの`$ref`を展開した後に、展開されたobjectを元に本処理を行う」といったアプローチを最初に試みたのですが、循環参照が発生する都合上、このアプローチは断念しました。
(最終的にはoneOfやanyOfといった仕様周りに心が折れて色々諦めました...)

このレポジトリはparserの提供がメインですので、展開を断念するという選択肢は難しいかと思いますが、何らかの防御策を提供された方が良いかと思い、issueとさせて頂きました.

Japanese sorry.

**Comment by tauren** [comment]
I'm running into this issue as well. Running this code:

```
import fs from "fs-extra"
import * as SchemaParser from "json-schema-parser"
let schema = fs.readJsonSync("test/fixtures/simpletree.json");
let deref = SchemaParser.parse(schema);
```

Using a basic tree schema in `simpletree.json`:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Basic Tree Schema",
  "description": "Causes stack RangeError: Maximum call stack size exceeded",
  "type": "object",
  "required": [ "id" ],
  "properties": {
     "id": {
        "type": "string",
        "description": "The node id"
     },
     "children": {
        "type": "array",
        "items": { "$ref": "#" }
     }
  }
}
```

Results in this error:

```
Stack:
RangeError: Maximum call stack size exceeded
    at unescape (/Users/tauren/test/node_modules/json-schema-parser/node_modules/json-pointer/index.js)
    at Array.map (native)
    at Function.parse (/Users/tauren/test/node_modules/json-schema-parser/node_modules/json-pointer/index.js:199:45)
    at Function.get (/Users/tauren/test/node_modules/json-schema-parser/node_modules/json-pointer/index.js:50:25)
    at parse (/Users/tauren/test/node_modules/json-schema-parser/lib/parser.js:13:29)
    at /Users/tauren/test/node_modules/json-schema-parser/lib/parser.js:18:17
    at Array.forEach (native)
    at parse (/Users/tauren/test/node_modules/json-schema-parser/lib/parser.js:14:28)
    at /Users/tauren/test/node_modules/json-schema-parser/lib/parser.js:18:17
    at Array.forEach (native)
```
